version: '3'

services:
  backend:
    environment:
      - DJANGO_DEBUG=false
      - DJANGO_SETTINGS_MODULE=config.settings_prod
  frontend:
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 80:80
    depends_on:
      - backend