version: '3.9'

services:
  backend:
    build: "./backend"
    environment:
      - DJANGO_DEBUG=true
      - DJANGO_SETTINGS_MODULE=config.settings
    ports:
      - "8000:8000"

  frontend:
    image: node:16
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
    ports:
      - "3000:3000"